### ISSUE TITLE
Authenticate as Owner (Resource Owner Password Credentials Grant)

### ISSUE THREAD

**Issue by holymp2006** [gabrielsomoza/oauth2-middleware#11]
hi,
The documentation doesn't mention how to implement "Resource Owner Password Credentials Grant".
Or maybe I'm missing something.

**Comment by gsomoza** [comment]
You're right, it doesn't mention that, thanks for the suggestion. I'll look into this when I get a chance. 

If in the meantime you happened to already figure out how to do it then please feel free to open a pull request with some docs, we'd greatly appreciate that!

**Comment by gsomoza** [comment]
Actually, now that I think a bit more about this, the password grant flow is something that would happen outside of the scope of this plugin. 

This plugin is only useful to automatically update requests going through a middleware pipeline by e.g. adding the `Bearer` header with an existing token. But the actual retrieval of the token is mean to happen outside the scope of this plugin.

In other words the application using this plugin would do the following:

1. Is there an Access Token available?
    * If "no", then go through whichever flow is necessary in order to get an initial access token before continuing with the next step.
2. Initialise the middleware with the Access Token and add the middleware to the pipeline.
3. The middleware will try to automatically refresh that token using the refresh token (if available). It will also inject the access token into every request using the token service that you provided to the middleware (e.g. `Bearer`).

I hope this makes sense. I'll consider adding a simplified version of this text to the main README so it's clear from the beginning what this library can or cannot do when it comes to OAuth2.

UPDATE: I inverted the use of authenticate/authorize in the second paragraph.
UPDATE2: simplified that paragraph again cause those weren't the most accurate terms. I hope it's more clear what I mean now.
