### ISSUE TITLE
It should be "Authorization" header, not "Authentication"

### ISSUE THREAD

**Issue by geekdevs** [gabrielsomoza/oauth2-middleware#3]
I that see you add "Authentication: Bearer {token}" header to the requests.
But this is not correct, it should be "Authorization: Bearer {token}" instead.

See https://tools.ietf.org/html/rfc6750#section-2.1

**Comment by gsomoza** [comment]
Oh, you're right! thanks, a bit of a brain fart on my part ;)

**Comment by gsomoza** [comment]
Should be fixed, thanks for the feedback!

**Comment by geekdevs** [comment]
@gsomoza awesome, thanks!

**Comment by geekdevs** [comment]
@gsomoza Any idea why it is still 0.2.1 on packagist https://packagist.org/packages/somoza/oauth2-client-middleware?

**Comment by gsomoza** [comment]
Oh, looks like the Packagist hook didn't work for some reason... Just updated it manually.

**Comment by geekdevs** [comment]
@gsomoza Thanks! Aslo is there any particular reason why you authenticate GET requests only?

```
if ($request->getMethod() !== 'GET'
            || $request->hasHeader('Authentication')
            || $request->getUri() == $this->provider->getBaseAuthorizationUrl()
        ) {
            return $request;
        }
```

**Comment by gsomoza** [comment]
This library was part of an application that only needed to authorize GET requests (other methods were either disallowed or had a legacy authentication system) so looks like I just forgot to remove that conditional there :)

Thanks for catching this (great feedback so far!). I made the fix and will tag a new release.

**Comment by geekdevs** [comment]
@gsomoza Thanks! Please also check my PR https://github.com/gsomoza/oauth2-middleware/pull/4
