### ISSUE TITLE
Support for league/oauth2-client v.2

### ISSUE THREAD

**Issue by geekdevs** [gabrielsomoza/oauth2-middleware#8]
Please add support for league/oauth2-client v.2. Looks like it should be as easy as changing the version at composer (e.g ^1.2.0|^2.2.0)

**Comment by hellboy81** [comment]
@geekdevs  Have u telegram account?

**Comment by gsomoza** [comment]
Will do this asap. PRs (with accompanying tests) are welcome of course.

**Comment by geekdevs** [comment]
@hellboy81 yes, my username is geekdevs.
@gsomoza thanks. This is just version changing, I don't think that there will be more tests needed.
